# Generated by Django 5.1.5 on 2025-01-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselling',
            name='category',
        ),
        migrations.RemoveField(
            model_name='counselling',
            name='gmail_addresses',
        ),
        migrations.RemoveField(
            model_name='counselling',
            name='images',
        ),
        migrations.RemoveField(
            model_name='counselling',
            name='phone_numbers',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Gmail',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Counselling',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
